services:
  # =====================================================
  # MinIO Object Storage Server Service
  # =====================================================
  minio-server:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: ${MINIO_SERVER_CONTAINER}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_EXTERNAL_PORT}:${MINIO_INTERNAL_PORT}"
    command: server /data

    volumes:
      - ${MINIO_DATA_PATH}:/data

# =====================================================
# Volumes Configuration
# =====================================================
volumes:
  minio-data:
    driver: local